name: connectcall
description: Connect with anyone, anywhere. A 1-to-1 audio/video calling app built with Flutter.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.9.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_riverpod: ^2.5.1
  go_router: ^14.2.0
  intl: ^0.19.0
  equatable: ^2.0.5
  firebase_core: ^3.4.1
  firebase_auth: ^5.2.1
  cloud_firestore: ^5.4.0
  flutter_dotenv: ^6.0.1
  permission_handler: 12.0.1
  zego_uikit_prebuilt_call: ^4.24.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - .env

dependency_overrides:
  zego_zim:
    path: third_party/zego_zim
  flutter_ringtone_player:
    path: third_party/flutter_ringtone_player
  flutter_volume_controller:
    path: third_party/flutter_volume_controller
  screen_brightness_android:
    path: third_party/screen_brightness_android
  zego_express_engine:
    path: third_party/zego_express_engine
  zego_uikit:
    path: third_party/zego_uikit
  zego_uikit_signaling_plugin:
    path: third_party/zego_uikit_signaling_plugin
  zego_uikit_prebuilt_call:
    path: third_party/zego_uikit_prebuilt_call
  zego_zpns:
    path: third_party/zego_zpns
